%%  Example: equivalent circuit model of lithium-ion battery cell
%   Load C-rate: 0.5, 1, 2, 3
%   NOTE: 1C = 1*Q_max_Ah, numerically
%   Avaliable typs of LIB cell
%   NCR18650B, NCR20700B, NCR18500A
%
%   Repo:       LIBECM
%   Author:     WANG Mingkai
%   Date:       2025-09-25
% 
%% Change log
%
% 2025-09-25 - WANG Mingkai - Baseline version                      - V1.0*
%
%% ====================Start of codesection========================
%% Case 1: Simulate the algebraic ECM of NCR18650B LIB
% Data preparation and algebraic model evaluation
LIBparam    = LIBECM.cell.getLIB('NCR18500A');
Q_B_Ah      = 0 : 1e-2 : 0.99*LIBparam.Q_max_Ah;
Crate       = [0.5; 1; 2; 3];
I_B_A       = LIBparam.Q_max_Ah.*Crate;

% Plot
figure('DefaultAxesFontName','Times New Roman');
set(gcf,...
    'units','normalized',...
    'Position',[0.3276    0.3194    0.2469    0.2463],...
    'color',[1,1,1]);
hold on;
for ii = 1 : numel(I_B_A)
    U_B_V = LIBECM.cell.mdlAlgebraic(Q_B_Ah, I_B_A(ii), LIBparam);
    plot(Q_B_Ah,U_B_V,'-','linewidth',2.0);
end

xlabel('$Q_B\mathrm{[Ah]}$','interpreter','latex');
ylabel('$U_B\mathrm{[V]}$','interpreter','latex');
grid on;
grid minor;
set(gca,'LineWidth',1.0,...
    'fontweight','bold',...
    'fontsize',12,...
    'LooseInset',get(gca,'TightInset'),...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'XColor'      , [.0 .0 .0], ...
    'YColor'      , [.0 .0 .0]);
legend('0.5C','1C','2C','3C',...
    'location','best',...
    'NumColumns',1);

%% Case 2: Simulate the dynamic ECM of NCR18650B LIB
LIBparam    = LIBECM.cell.getLIB('NCR18650B');
I_B_A       = [4,6,8];

% Create a figure window
figure('DefaultAxesFontName','Times New Roman');
set(gcf,...
    'units','normalized',...
    'Position',[0.3276    0.3194    0.2469    0.2463],...
    'color',[1,1,1]);
hold on;

% Call ode45 for simulation
SimSet.x0       = zeros(2,1);                                               % Initial states£ºQ_B_Ah, U_P_V
SimSet.tspan_s  = 0:2:3600;                                              	% Time span
for ii = 1 : numel(I_B_A)
    SimSet.odeFunc = @(t, x)LIBECM.sim.cellWrapper(t,x,I_B_A(ii),LIBparam);	% Function handle for ECM simulation
    SimSet.Opt = odeset('Events',@(t,x)LIBECM.sim.endEvent(t,x,LIBparam)); 	% Declare the terminal event
    [SimRes.t_s,SimRes.x,SimRes.te,SimRes.xe,SimRes.ie] =...
        ode45(SimSet.odeFunc,SimSet.tspan_s,SimSet.x0,SimSet.Opt);
    SimSet.nt = numel(SimRes.t_s);
    [~,U_B_V] = LIBECM.sim.cellWrapper(SimRes.t_s,SimRes.x.',I_B_A(ii).*ones(1,SimSet.nt),LIBparam);
    plot(SimRes.x(:,1),U_B_V,'-','linewidth',2.0);
end

% Adjust figure and axis properties
xlabel('$Q_B\mathrm{[Ah]}$','interpreter','latex');
ylabel('$U_B\mathrm{[V]}$','interpreter','latex');
grid on;
grid minor;
set(gca,'LineWidth',1.0,...
    'fontweight','bold',...
    'fontsize',12,...
    'LooseInset',get(gca,'TightInset'),...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.01 .01] , ...
    'XMinorTick'  , 'off'      , ...
    'YMinorTick'  , 'off'      , ...
    'XColor'      , [.0 .0 .0], ...
    'YColor'      , [.0 .0 .0]);
legend('$I=4\:\mathrm{A}$','$I=6\:\mathrm{A}$','$I=8\:\mathrm{A}$',...
    'location','best',...
    'interpreter','latex',...
    'NumColumns',1);
axis([0 3.5 2.5 4.0]);
%% ========================End of File=============================
